version: '3.1'

services:
  app:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
        - AWS_SECRET_KEY_NAME=$AWS_SECRET_KEY_NAME
        - AWS_REGION=$AWS_REGION
        - AWS_OUTPUT=$AWS_OUTPUT
        - GIT_TOKEN=$GIT_TOKEN
        - MYSQL_USER=$MYSQL_USER
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - SERVICE_IP=$SERVICE_IP
        - SERVICE_PORT=$SERVICE_PORT
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - redis

  consul:
    image: consul:latest
    container_name: consul
    command: ["agent", "-dev", "-client", "0.0.0.0", "-ui", "-bind", "0.0.0.0"]
    environment:
      - 'CONSUL_BIND_INTERFACE=eth0'
      - 'CONSUL_DATACENTER=my-dc'
      - 'CONSUL_SERVER=false'
      - 'CONSUL_CLIENT_ADDR=0.0.0.0'
      - 'CONSUL_ENABLE_SCRIPT_CHECKS=true'
      - 'CONSUL_RETRY_JOIN=10.0.0.12'
      - 'CONSUL_CORS_ALLOWED_ORIGINS=http://localhost:*'
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
      - "80:80"

  redis:
    container_name: auth-redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  mysql:
    container_name: auth-mysql
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      AWS_SECRET_KEY_NAME: $AWS_SECRET_KEY_NAME
    user: root
    ports:
      - "3306:3306"
volumes:
  mysql_data:
